Two new inscription editions and an attempt at translating them
ISicily/ISicily pull request #123
Opened 2021-03-05 12:35 UTC by noah-cashian

Might have messed up the pull request again - another abortive test?

2021-03-08 21:18 UTC, JonPrag requested changes
Dear Noah

Absolutely the right idea and broadly correct - well done. The issues here are almost all tiny peccadilloes (and all are noted in comments individually). In writing code the precision is however important: from a purely syntactical perspective in XML, the spaces must only be in the right places inside the tags; values on attributes must be in "" not in ' '; and a value on a ref needs the # on it. In the text, could you use u and v, rathe rthan just v; and could you aim to close up all space, except between individual words?
As I say, all very small things. Once the corrections are made commit them and repeat the pull request process, which will simply add them tot he existing pull request, and then I will approve and incorporate. 
many thanks!
Jonathan

2021-03-08 21:18 UTC, JonPrag commented on inscriptions/ISic000543.xml
> +                                    <expan><abbr>A</abbr><ex>vgvsti</ex></expan>
I think it's Aug(usti)?

2021-03-08 21:18 UTC, JonPrag commented on inscriptions/ISic000543.xml
> +                <!--Latin Q - 'auge' imperative seems awkward here, or am I just unused to epigraphic Latin?-->
surely a second name 'Auge' (Greek name): [http://clas-lgpn2.classics.ox.ac.uk/cgi-bin/lgpn_search.cgi?namenoaccents=%CE%91%CE%A5%CE%93%CE%97](http://clas-lgpn2.classics.ox.ac.uk/cgi-bin/lgpn_search.cgi?namenoaccents=%CE%91%CE%A5%CE%93%CE%97)

2021-03-08 21:18 UTC, JonPrag commented on inscriptions/ISic000543.xml
> +                <!--If Aug(usta) (libert), then: 'Publius Aelius Nigrianus, freedman of the emperor, (made) (this) for his most sacred wife Aelia, freedwoman of the emperor'-->
chaste or virtuous (or pure), rather than 'sacred'.

2021-03-08 21:18 UTC, JonPrag commented on inscriptions/ISic000543.xml
>                  <app loc="line 5"><note>Auria 1697: [..]IGR[..]NVS[..]; Gualtherus 1624: ΛIGRANIVS</note></app>
which leaves us with an interesting question, as to whether we think it's Nigranius or Nigrianus; the latter is however better attested from a quick look in Clauss Slaby.

2021-03-11 18:01 UTC, noah-cashian commented
Dear Jonathan,

Sorry for those silly mistakes, and thank you for pointing out where they
were. I've just made a new commit for both files and have pushed it to the
origin from my desktop GitHub app, although I'm not sure if this has been
automatically merged with the original pull request. Just in case, I
thought I'd email you to let you know.

All best,
Noah

On Mon, 8 Mar 2021 at 21:19, Jonathan Prag ***@***.***> wrote:

> *@JonPrag* requested changes on this pull request.
>
> Dear Noah
>
> Absolutely the right idea and broadly correct - well done. The issues here
> are almost all tiny peccadilloes (and all are noted in comments
> individually). In writing code the precision is however important: from a
> purely syntactical perspective in XML, the spaces must only be in the right
> places inside the tags; values on attributes must be in "" not in ' '; and
> a value on a ref needs the # on it. In the text, could you use u and v,
> rathe rthan just v; and could you aim to close up all space, except between
> individual words?
> As I say, all very small things. Once the corrections are made commit them
> and repeat the pull request process, which will simply add them tot he
> existing pull request, and then I will approve and incorporate.
> many thanks!
> Jonathan
> ------------------------------
>
> In inscriptions/ISic000329.xml
> <https://github.com/ISicily/ISicily/pull/123#discussion_r589652119>:
>
> > @@ -37,6 +37,10 @@
>
>  	    <respStmt>
>
>                      <name xml:id="system">system</name>
>
>                      <resp>automated or batch processes</resp>
>
> +                </respStmt>
>
> +                <respStmt>
>
> +                    <name xml:id='NCash' ref='https://orcid.org/0000-0002-8767-3368'>Noah Cashian</name>
>
>
> "NCash" not 'NCash', and " " for the ref also
> ------------------------------
>
> In inscriptions/ISic000329.xml
> <https://github.com/ISicily/ISicily/pull/123#discussion_r589652524>:
>
> > @@ -172,7 +176,8 @@
>
>  		<change when="2020-11-26" who="#SS">Simona Stoyanova restructured bibliography</change>
>
>  	    <change when="2020-12-22" who="#system">Updated Zenodo DOI</change>
>
>              	<change when="2021-01-19" who="#SS">renumbered files, uris and references</change>
>
> -	</listChange>
>
> +	              <change when='2021-03-04' who='#NCash'>Noah Cashian refined inscription edition and provided English translation</change>
>
>
> again, must use " " not ' '
> ------------------------------
>
> In inscriptions/ISic000329.xml
> <https://github.com/ISicily/ISicily/pull/123#discussion_r589652685>:
>
> > @@ -193,46 +198,38 @@
>
>      </facsimile>
>
>      <text>
>
>          <body>
>
> -            <div type="edition" xml:space="preserve" subtype="EDR" n="EDR141135" xml:lang="la">
>
> +            <div type="edition" xml:space="preserve" xml:lang="la" resp='#NCash'>
>
>
> " "
> ------------------------------
>
> In inscriptions/ISic000329.xml
> <https://github.com/ISicily/ISicily/pull/123#discussion_r589653412>:
>
> > -                        <ex>arcus</ex>
>
> -                    </expan>
>
> -                    Antonius<lb n="3"/>Syriacus vivus<lb n="4"/>hoc monumentum
>
> -                    <lb n="5"/>
>
> -                    <expan>
>
> -                        <abbr>sib</abbr>
>
> -                        <ex>i</ex>
>
> -                    </expan>
>
> -                    et suis
>
> -                    <expan>
>
> -                        <abbr>fec</abbr>
>
> -                        <ex>it</ex>
>
> -                    </expan>
>
> -                    .
>
> +            <lb n="1"/>
>
> +            <expan><abbr>d</abbr><ex>iis</ex></expan>
>
>
> normally dis not diis
> ------------------------------
>
> In inscriptions/ISic000329.xml
> <https://github.com/ISicily/ISicily/pull/123#discussion_r589657374>:
>
> > -                        <ex>i</ex>
>
> -                    </expan>
>
> -                    et suis
>
> -                    <expan>
>
> -                        <abbr>fec</abbr>
>
> -                        <ex>it</ex>
>
> -                    </expan>
>
> -                    .
>
> +            <lb n="1"/>
>
> +            <expan><abbr>d</abbr><ex>iis</ex></expan>
>
> +                <expan><abbr>m</abbr><ex>anibvs</ex></expan>
>
> +                    <expan><abbr>s</abbr><ex>acrum</ex></expan>
>
> +            <lb n="2"/>
>
> +            <expan><abbr>M</abbr><ex>arcvs</ex></expan>
>
> +                <g ref="#interpunct"/>
>
> +                    Antonivs
>
>
> I understand the thinking (there is only the letter 'v') in Latin, but it
> is normal lexical practice to distinguish consonantal 'v' from vowel 'v',
> and so to use 'v' for the consonantal letter and 'u' for the vowel (but
> always to use V for both in majuscule, i.e. diplomatic editions).
> ------------------------------
>
> In inscriptions/ISic000329.xml
> <https://github.com/ISicily/ISicily/pull/123#discussion_r589658585>:
>
> > -                    <expan>
>
> -                        <abbr>fec</abbr>
>
> -                        <ex>it</ex>
>
> -                    </expan>
>
> -                    .
>
> +            <lb n="1"/>
>
> +            <expan><abbr>d</abbr><ex>iis</ex></expan>
>
> +                <expan><abbr>m</abbr><ex>anibvs</ex></expan>
>
> +                    <expan><abbr>s</abbr><ex>acrum</ex></expan>
>
> +            <lb n="2"/>
>
> +            <expan><abbr>M</abbr><ex>arcvs</ex></expan>
>
> +                <g ref="#interpunct"/>
>
> +                    Antonivs
>
> +            <lb n="3"/>
>
> +            Syriacvs
>
> +                <g ref="#interpunct"/>
>
>
> for those symbols for which we have the unicode character, we add the
> symbol and place it within the g tags, so:
> <g ref="'#interpunct">·</g>
> You can find a list of all the ones we so encode (so far - if you find
> something new, tell me!), at:
> https://github.com/ISicily/ISicily/blob/master/alists/charDecl.xml
> ------------------------------
>
> In inscriptions/ISic000329.xml
> <https://github.com/ISicily/ISicily/pull/123#discussion_r589659279>:
>
> > +            <expan><abbr>M</abbr><ex>arcvs</ex></expan>
>
> +                <g ref="#interpunct"/>
>
> +                    Antonivs
>
> +            <lb n="3"/>
>
> +            Syriacvs
>
> +                <g ref="#interpunct"/>
>
> +                    vivvs
>
> +            <lb n="4"/>
>
> +            hoc
>
> +                monvmentvm
>
> +            <lb n="5"/>
>
> +            <expan><abbr>sib</abbr><ex>i</ex></expan>
>
> +                et
>
> +                    svis
>
> +                        <g ref="#interpunct"/>
>
> +                            <expan><abbr>fe<hi rend = 'small'>c</hi></abbr><ex>it</ex></expan>
>
>
> <hi rend="small"> (i.e. close up the spaces except between the element
> name and attribute and use " not ')
> ------------------------------
>
> In inscriptions/ISic000329.xml
> <https://github.com/ISicily/ISicily/pull/123#discussion_r589662573>:
>
> >                  </ab>
>
>                  <!--This EDR text 141135 originally came via the Europeana EAGLE project, http://www.eagle-network.eu/-->
>
>              </div>
>
>              <div type="apparatus">
>
>                  <p><!--external apparatus criticus (if applicable)--></p>
>
>              </div>
>
> -            <div type="translation">
>
> -                <p><!--translation(s) - add @xml:lang for 'en' or 'it' to div--></p>
>
> +            <div xml:lang='en' type="translation" resp='#NCash'>
>
> +                <p>Sacred to the Manes of Marcus Antonius Syriacus, who while alive made this monument for himself and his relatives</p>
>
>
> Strictly speaking, can't be 'of marcus...', since he is in the nominative.
> So, 'Sacred to the spirits of the underworld. Marcus Antonius Syriacus made
> this monument for himself and his relatives while living'. I suppose if I
> were being really picky, I'm not sure if we should prejudge that 'suis'
> means just relatives, [...]

2021-03-11 22:15 UTC, JonPrag approved these changes
Excellent, many thanks - use of spaces all looks good now

2021-03-11 22:16 UTC, merged