Text and translation updates
ISicily/ISicily pull request #129
Opened 2021-03-10 17:00 UTC by MhewittOx

2021-03-11 22:52 UTC, JonPrag requested changes
Just some very small changes / suggestions - generally excellent!

2021-03-11 22:52 UTC, JonPrag commented on inscriptions/ISic000333.xml
> +                    <lb n="3"/>I <gap reason="lost" quantity="9" unit="character" precision="low"/>vo
the 'I' should probably go in `<orig>` to mark letters clear but of which no sense can be made.

also, ideally lose the initial space before Arruntia in line 1.

2021-03-11 22:52 UTC, JonPrag commented on inscriptions/ISic000333.xml
>                  <!--This EDR text 141163 originally came via the Europeana EAGLE project, http://www.eagle-network.eu/-->
this comment line can now be deleted.

2021-03-11 22:52 UTC, JonPrag commented on inscriptions/ISic000335.xml
> +                <lb n="4"/>meses <num value="9">VIIII</num>
I would suggest that one would encode the erroneous/non-standard form of 'menses' thus:
`<choice><orig>meses</orig><reg>menses</reg></choice>`

2021-03-11 22:52 UTC, JonPrag commented on inscriptions/ISic000335.xml
> +                <lb n="4"/>meses <num value="9">VIIII</num>
Further, you could do the same thing to Bictoria/Victoria in line 1?

2021-03-11 22:52 UTC, JonPrag commented on inscriptions/ISic000338.xml
> +                    <lb n="1"/><expan><abbr>D</abbr><ex>is</ex></expan> <g ref="#interpunct">·</g> <expan><abbr>M</abbr><ex>anibus</ex></expan> <g ref="#interpunct">·</g> <expan><abbr>M</abbr><ex>ani
I think you've ended up repeating Manibus by mistake? DMS?

2021-03-11 22:52 UTC, JonPrag commented on inscriptions/ISic000338.xml
> +                    <lb n="2"/><expan><abbr>M</abbr><ex>arcus</ex></expan> <g ref="#interpunct">·</g> Caepario
Marco?

2021-03-11 22:52 UTC, JonPrag commented on inscriptions/ISic000338.xml
>                  <!--This EDR text 141165 originally came via the Europeana EAGLE project, http://www.eagle-network.eu/-->
you can delete this comment line

2021-03-11 22:52 UTC, JonPrag commented on inscriptions/ISic000339.xml
> +                    <lb n="1"/><expan><abbr>D</abbr><ex>is</ex></expan> <g ref="#interpunct">·</g><expan><abbr>M</abbr><ex>anibus</ex></expan> <g ref="#interpunct">·</g> <expan><abbr>s</abbr><ex>acru
add a space after the closing `</g>` of the first interpunct

2021-03-11 22:52 UTC, JonPrag commented on inscriptions/ISic000339.xml
> +                    r<lb n="5"/>Lupercus.
rogue r before the `<lb>`? And delete the final period.

2021-03-11 22:52 UTC, JonPrag commented on inscriptions/ISic000339.xml
>                  <!--This EDR text 141166 originally came via the Europeana EAGLE project, http://www.eagle-network.eu/-->
can deletet eh comment line

2021-03-11 22:52 UTC, JonPrag commented on inscriptions/ISic000343.xml
>                  <!--This EDR text 141170 originally came via the Europeana EAGLE project, http://www.eagle-network.eu/-->
can delete comment line

2021-03-12 07:47 UTC, MhewittOx commented
Thanks, hopefully that should all be resolved now!

2021-03-12 08:53 UTC, JonPrag approved these changes
all good, thanks!

2021-03-12 08:53 UTC, merged