Update ISic000482.xml
ISicily/ISicily pull request #136
Opened 2021-03-15 12:12 UTC by alessandrarocchetti

2021-03-15 12:14 UTC, alessandrarocchetti commented on inscriptions/ISic000482.xml
>                      <!--note that 7208 is on the same block. Inscribed on a column capital: to Trajan, with titles, and ends I.D.D.D. - but possibly this should be LDDD, given that the bottom edge is
I think the emperor is Hadrian not Trajan ... I might be wrong though

2021-04-13 15:27 UTC, JonPrag requested changes
Thanks Alexandra - sorry it's taken me so long- various minor things to tweak.

2021-04-13 15:27 UTC, JonPrag commented on inscriptions/ISic000482.xml
> +                    <lb n="2"/><supplied reason="lost">parthi</supplied>ci <g ref="#interpunct">·</g> <expan><abbr>f</abbr><ex>elix</ex></expan> <g ref="#interpunct">·</g> <name>Traiano</name> <name>
filio, not felix (son of the deified Traianus Parthicus)

2021-04-13 15:27 UTC, JonPrag commented on inscriptions/ISic000482.xml
> +                    <lb n="3" break="no"/><supplied reason="lost">an</supplied>o</name> <g ref="#interpunct">·</g> <expan><abbr>Aug</abbr><ex>usto</ex></expan> <expan><abbr>pontif</abbr><ex>ice</ex><
pontifici (dative, not ablative)

2021-04-13 15:27 UTC, JonPrag commented on inscriptions/ISic000482.xml
> +                    <lb n="4"/><expan><abbr>pot</abbr><ex>esta</ex></expan> <g ref="#interpunct">·</g> <num value="3">III</num> <g ref="#interpunct">·</g> <expan><abbr>co</abbr><ex>n</ex>s<ex>ule</ex
consuli, not consule

2021-04-13 15:27 UTC, JonPrag commented on inscriptions/ISic000482.xml
> +                    <lb n="5"/><expan><abbr><choice><reg>l</reg><orig>i</orig></choice></abbr><ex>ocus</ex></expan> <expan><abbr>d</abbr><ex>atus</ex></expan> <expan><abbr>d</abbr><ex>ecreto</ex></ex
unclear for the L, not reg versus orig, so:
`<expan><abbr><unclear>l</unclear></abbr><ex>ocus</ex></expan>`

2021-04-13 15:27 UTC, JonPrag commented on inscriptions/ISic000482.xml
> +                <p>For the emperor Caesar Trajan Hadrian Augustus, son of the diefied emperor Trajan, victor over the Partian, chief priest, holder of the tribunician powers three times, consul three
<p>For the Emperor Caesar Trajan Hadrian Augustus, son of the deified Trajan Parthicus, chief priest, holder of the tribunician power for the third time, consul for the third time. The place was given by decree of the town councillors.</p>

2021-04-16 10:34 UTC, JonPrag approved these changes

2021-04-16 10:34 UTC, merged