Updating 4 inscriptions
ISicily/ISicily pull request #151
Opened 2021-04-23 15:08 UTC by Jamesjhua

ISic000471, ISic000415, ISic000399, ISic000395

2021-04-30 10:19 UTC, Jamesjhua commented
Adding an additional 5 inscriptions from 30 April ; ISic 000370, 000375, 000377, 000380, 000478

2021-05-07 10:02 UTC, JonPrag requested changes
Good work on this, thank you - various awkward things, some of which only presented today

2021-05-07 10:02 UTC, JonPrag commented on inscriptions/ISic000478.xml
> +                    <lb n="2"/><name>Tesorus</name>
thesaurus (i.e. treasure), not a name (so leave as is, but remove name tag)

2021-05-07 10:02 UTC, JonPrag commented on inscriptions/ISic000478.xml
> +                <p>Tesorus (dedicates this) to Hercules</p>
'treasure of hercules'

2021-05-15 08:33 UTC, Jamesjhua commented
Made corrections and 3 new inscriptions (2 Greek)

2021-05-18 11:09 UTC, JonPrag approved these changes
Thanks James; I've directly amended the last two Greek texts - important not to rely on the PHI texts, which are mostly rather garbled due to the conversion processes out of the original betacode, and to use one or more of the published texts as your direct basis.

2021-05-18 11:12 UTC, merged

2021-05-18 12:19 UTC, Jamesjhua commented
Dear Jonathan, 

Thanks for letting me know - I’ll use the IG original text for the next ones. On a side note, would I be allowed to join just for the first hour (9-10am) for this Friday, please? I have a tutorial at 10am, but I can move it till later if needed.

Thanks.
All the best,
James


> On 18 May 2021, at 12:09 pm, Jonathan Prag ***@***.***> wrote:
> 
> 
> @JonPrag approved this pull request.
> 
> Thanks James; I've directly amended the last two Greek texts - important not to rely on the PHI texts, which are mostly rather garbled due to the conversion processes out of the original betacode, and to use one or more of the published texts as your direct basis.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ISicily/ISicily/pull/151#pullrequestreview-661943286>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AS2MHYM2YX5W3P52Q4KL62LTOJDHDANCNFSM43O2IQJA>.
>