iSic Editing 11 June
ISicily/ISicily pull request #175
Opened 2021-06-11 10:12 UTC by AlexAAntoniou

18 Inscriptions

2021-06-23 16:38 UTC, JonPrag requested changes
Bits and pieces, but nothing major!

2021-06-23 16:38 UTC, JonPrag commented on inscriptions/ISic001357.xml
> +                    <lb n="4"/>ζῶν <orig>ΚΕΕΙΜΕ</orig>
NB Califano interprets thus: 
![image](https://user-images.githubusercontent.com/25080386/123134332-9657c380-d448-11eb-9829-63c930075e32.png)

2021-06-23 16:38 UTC, JonPrag commented on inscriptions/ISic001357.xml
> +                    <lb n="1"/><expan><abbr>πρ</abbr><ex>ὸ</ex><abbr>ς</abbr></expan> καλανδ<supplied reason="lost">ῶν</supplied>
NB the ς is actually ϛ, i.e. sampi, the numeral 6, not part of the preposition

2021-06-23 16:38 UTC, JonPrag commented on inscriptions/ISic001368.xml
>                      <lb n="5"/>τρειῶν εἰδῶν
code the numeral, although in words

2021-06-23 16:38 UTC, JonPrag commented on inscriptions/ISic003700.xml
> +                <p>The purchase of(?) Palladios, the spouse of Pelagia. Pelagia having passed 11 [days] before the Kalends of [...], having died [...] of September, here she, who had one husband, lie
i think it's fine - agorasia is a standard formulation for the purchase of the loculus /tomb

2021-06-24 07:11 UTC, AlexAAntoniou commented
@JonPrag changes now made, and my first attempt at adding metadata for a handful of ILipara inscriptions now added.

2021-06-24 14:23 UTC, JonPrag approved these changes
Dear Alex
this is all excellent, and the Lipara files look very good. We might, perhaps, discuss the question of adding geographic coordinates on the provenance element, but let's have a conversation about that in more detail, perhaps on Friday.

2021-06-24 14:23 UTC, merged