Termini editions based on autopsy
ISicily/ISicily pull request #253
Opened 2023-08-18 05:33 UTC by AlexAAntoniou

ISic 128, 163, 178, 206 (4 Files, 18 Aug)

2023-08-18 05:33 UTC, AlexAAntoniou commented
First attempt at this, so please do let me know where I'm getting it wrong!

2023-08-19 07:12 UTC, JonPrag requested changes
Excellent, jus tminor things and a need to revise the name tagging! thankyou!

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000128.xml
> +                    <lb n="1"/><persName type="attested"><expan><abbr>P</abbr><ex>ublius</ex></expan></persName> <g ref="#interpunct">·</g> <persName type="attested">Antistius</persName> <g ref="#int
NB `<persName>` goes once around the complete name, so `<persName type="attested">Publius Antisitius Publii filius Claudia (tribu) Cavarianus</persName>`. The patronym is then tagged with persName internally to that, as recording a separate person. Each onomastic element gets `<name>` around it, and we put type="patronym" on name element around the Publi in this case. We are not bothering to encode the others, but you can see the principles at https://github.com/ISicily/ISicily/wiki/Encoding:-text#named-entities and could encode praenomen, cognomen, etc. if you wanted to... Note too the full formally correct encoding for the tribal...

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000128.xml
> +                    <app><note>Text from autopsy</note></app>
It would be good to record at this point any divergences from the ILTermini text, in the form, e.g. `<app loc="1"><note>Bivona: wibble</note></app>`

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000128.xml
>              <div type="translation" xml:lang="en" resp="#TA">
you can add your resp to any div that you amend, so e.g. `<resp="#TA #AA">`, not least the text div!

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000128.xml
>              <div type="commentary">
add your resp on the commentary

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000163.xml
> +                                <support><p>Plague broken into four pieces, with irregular edges. Small fragment missing at the centre of the reattached pieces. Rear of plaque is relatively flat.</p>
plaque!

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000163.xml
> +                        <provenance type="observed" subtype="autopsied" when="2022-07-06" resp="#JP">Antoniou, 2022-07-06. On display in Museo Civico Baldassare Romano.</provenance>
resp #AA

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000163.xml
> +                        <provenance type="found" subtype="discovered" when="1907-08">Found, together with <ref target="http://sicily.classics.ox.ac.uk/inscription/ISic000161">ISic000161</ref>, <ref t
excellent!

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000163.xml
> +                    <lb n="2"/><persName type="attested">Cornelia</persName> <g ref="#interpunct">·</g> <persName type="attested">Scepsis</persName> <g ref="#interpunct">·</g>
see previous comments on naming tags

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000163.xml
>              <div type="commentary">
resp AA

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000178.xml
> +                                <support><p>Block of white marble with orange discolouration on sides. Left and top sides are intact, but with chipping along top edge. Bottom right corner is broken.
block or thick plaque?

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000178.xml
> +                        <provenance type="observed" subtype="autopsied" when="2022-07-06" resp="#JP">Antoniou, 2022-07-06. On display in Museo Civico Baldassare Romano</provenance>
#AA

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000178.xml
> +                <p>Cestiae are relatively common in Thermae Himeraeae. Roman citizens of tribe Quirina are attested elsewhere in Thermae Himeraeae, see <ref target="http://sicily.classics.ox.ac.uk/in
something funny in the final sentence? On tribals, for what it's worth, Prag, J. R. W. (2010). Sicilia Romana tributim discripta. In M. Silvestrini (Ed.), Le tribù romane. Atti della XVIe Rencontre sur l’épigraphie (Bari 8-10 ottobre 2009) (pp. 305–311). Edipuglia.

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000206.xml
> +                                    <height unit="mm">43-36</height>
reverse number order

2023-08-19 07:12 UTC, JonPrag commented on inscriptions/ISic000206.xml
> +                    <lb n="2"/><persName type="attested">Rodia</persName>
as previous, persName around the whole, name around each element.

2023-08-21 08:22 UTC, AlexAAntoniou commented
Thanks Jon. Changes made – fingers crossed I've gotten it right this time round.

2023-08-22 12:14 UTC, JonPrag approved these changes
excellent, many thanks!
j

2023-08-22 12:15 UTC, merged